FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder
WORKDIR /app
COPY pyproject.toml uv.lock ./

# copy specific code files for the inventory service
COPY services/inventory-service/ services/inventory-service/

# Install dependencies for the inventory service
RUN uv sync --package inventory-service --frozen --no-dev 
COPY . .

FROM python:3.12-slim-bookworm
WORKDIR /app
COPY --from=builder /app /app
ENV PATH="/app/.venv/bin:$PATH"
# Standard FastAPI execution
CMD ["fastapi", "run", "services/inventory-service/main.py", "--port", "8000", "--host", "0.0.0.0"]