services:
  user-service:
    build:
      context: .
      dockerfile: services/user-service/dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:password@db:5432/user_db
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   
  product-service:
    build:
      context: .
      dockerfile: services/product-service/dockerfile
    


volumes:
  postgres_data:
