#Stage 1: The builder

FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim as builder
ENV UV_COMPLETE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_HTTP_TIMEOUT=120
WORKDIR /app


# copy dependency files
COPY pyproject.toml uv.lock ./

# copy specific code files

COPY services/product-service/ services/product-service/

# Install dependencies for the product service
RUN uv sync --package product-service --frozen --no-dev


# Copy rest of the code

COPY . .




#Stage 2: The final Image
FROM python:3.12-slim-bookworm
WORKDIR /app

# copy the env and code from the builder
COPY --from=builder /app/.venv /app/.venv
COPY --from=builder /app/services /app/services

# put the virtual env on the path.
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app/services/product-service"

# run the FASTAPI server
CMD ["python" ,"services/product-service/main.py","--port","8001","--host","0.0.0.0"]