[project]
name = "product-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sumedh-Lenovo", email = "sumedh85@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "grpcio>=1.83.1",
    "grpcio-tools>=1.83.1",
]

[project.scripts]
product-service = "product_service:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
